# Generated by Django 4.2.28 on 2026-02-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
